name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  # Job 1 - Run Tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Unit Tests
        run: npm test
        working-directory: ./frontend

  # Job 2 - Security Scan
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Security Scan
        run: |
          echo "Running Trivy Scan"
          docker run --rm -v $PWD:/project aquasec/trivy fs /project

  # Job 3 - Build and Push Docker Image
  docker-build:
    needs:
      - test
      - security-scan

    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build Image
      - name: Build Docker Image
        run: |
          docker build -t webtravel-frontend ./frontend

      # Tag Image
      - name: Tag Image
        run: |
          docker tag webtravel-frontend:latest \
          867138158694.dkr.ecr.eu-north-1.amazonaws.com/webtravel-frontend:latest

      # Push Image
      - name: Push Image
        run: |
          docker push 867138158694.dkr.ecr.eu-north-1.amazonaws.com/webtravel-frontend:latest
