name: Docker Image CI

on:
  push:
    branches: ["main"]


jobs:

  # 1. SonarQube Scan
  sonarqube-scan:

    runs-on: ubuntu-latest

    steps:

      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # SonarQube Analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5

        env:

          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

          SONAR_HOST_URL: https://sonarcloud.io



  # 2. Build and Push Docker Image

  build:

    runs-on: ubuntu-latest

    needs:
      - sonarqube-scan


    steps:


      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4



      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: eu-north-1



      # 3. Login to Amazon ECR
      - name: Login to Amazon ECR

        id: login-ecr

        uses: aws-actions/amazon-ecr-login@v2



      # 4. Build Docker image (backend folder)
      - name: Build Docker image

        run: |

          docker build \
          -t webtravel-backend \
          ./backend



      # 5. Tag Docker image for ECR
      - name: Tag Docker image

        run: |

          docker tag webtravel-backend:latest \
          867138158694.dkr.ecr.eu-north-1.amazonaws.com/webtravel-backend:latest



      # 6. Push Docker image to ECR
      - name: Push to ECR

        run: |

          docker push \
          867138158694.dkr.ecr.eu-north-1.amazonaws.com/webtravel-backend:latest
